export const ONTARIO_UNIVERSITIES: string[] = [
  'Algonquin College',
  'Brock University',
  'Cambrian College',
  'Canadore College',
  'Carleton University',
  'Centennial College',
  'Conestoga College',
  'Confederation College',
  'Durham College',
  'Fanshawe College',
  'Fleming College',
  'George Brown College',
  'Georgian College',
  'Humber College',
  'Lambton College',
  'Lakehead University',
  'Laurentian University',
  'McMaster University',
  'Mohawk College',
  'Niagara College',
  'Nipissing University',
  'Northern College',
  'OCAD University',
  'Ontario Tech University',
  'Queen\'s University',
  'Redeemer University',
  'Royal Military College',
  'Ryerson University (Toronto Metropolitan)',
  'Saint Paul University',
  'Seneca College',
  'Sheridan College',
  'Sir Sanford Fleming College',
  'St. Clair College',
  'St. Lawrence College',
  'Trent University',
  'University of Guelph',
  'University of Ottawa',
  'University of Toronto',
  'University of Waterloo',
  'University of Windsor',
  'Western University',
  'Wilfrid Laurier University',
  'York University',
  'Collège Boréal',
  'La Cité collégiale',
];

export const DOLLAR_PER_CREDIT = 800;
